#Sourcing external config files
source=~/.config/hypr/configs/exec.conf
source=~/.config/hypr/configs/keybinds.conf
source=~/.config/hypr/configs/monitors.conf
source=~/.config/hypr/configs/variables.conf
# source=~/.config/hypr/configs/window_rules.conf

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = yes
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

general {
    gaps_in = 3
    gaps_out = 5
    border_size = 2
    # col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.active_border = rgba(00ff99ee) rgba(00ff33ee) 45deg
    col.inactive_border = rgba(595959aa)

    layout = dwindle
}

misc {
    disable_hyprland_logo = false
}

decoration {
    rounding = 5
    # blurls = lockscreen
    # active_opacity = 0.8
    active_opacity = 1
    # inactive_opacity = 0.8
    inactive_opacity = 0.7
    fullscreen_opacity = 1
    # drop_shadow = yes
    # shadow_range = 4
    # shadow_render_power = 3
    # col.shadow = rgba(1a1a1aee)
}

animations {
    enabled = yes
    bezier = myBezier, 0.16, 1, 0.3, 1

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, myBezier, popin 80%
    animation = border, 1, 10, myBezier
    animation = fade, 1, 7, myBezier
    animation = workspaces, 1, 5, default
}

master {
    new_status = master
    #new_on_top = true
}

# gestures {
#     workspace_swipe = on
# }

dwindle {
    pseudotile = yes 
    preserve_split = yes 
}
