osc=no

[Idle]
profile-cond=p["idle-active"]
profile-restore=copy-equal
title=' '
keepaspect=no
background=1

save-position-on-quit=yes
# The default volume of mpv when you open it
volume=95
blend-subtitles=yes
screenshot-directory=~/Pictures/Screenshots
screenshot-format=png
osc=no
hwdec=auto
dscale=bilinear
slang=en
alang=en
