source=~/.config/hypr/configs/variables.conf

# Master layout
# bind = $mainMod, SPACE, layoutmsg, orientationnext
# bind = $mainMod, comma, layoutmsg, addmaster
# bind = $mainMod, period, layoutmsg, removemaster
# bind = $mainMod, RETURN, layoutmsg, swapwithmaster

# Apps

bind = $mainMod, T, exec, $term
bind = $mainMod, E, exec, $files
bind = $mainMod, C, exec, $ide
bind = $mainMod, B, exec, $browser
bind = $mainMod SHIFT, B, exec, $incognito
bind = $mainMod SHIFT, J, exec, $jupyter
bind = CTRL SHIFT, B, exec, $taskmgr
bind = $mainMod CTRL, 0, exec, $notify
bind = $mainMod CTRL, 1, exec, $music
bind = $mainMod CTRL, 2, exec, $connections
bind = $mainMod CTRL, 3, exec, $text
bind = $mainMod, SPACE, exec, $rofi
bind = $mainMod, K, exec, $eww
bind = $mainMod, M, exec, $powerMenu
bind = $mainMod, Q, killactive
bind = $mainMod, L, exec, $lock
bind = $mainMod, r, exec, $kill 
bind = $mainMod SHIFT, Q, exit
bind = $mainMod, V, togglefloating
bind = $mainMod, P, pseudo
bind = $mainMod, J, togglesplit
bind = $mainMod, F, fullscreen
bind = $mainMod, W, exec, $bar
bind = ALT, F4, killactive

# Special Keys / Hot Keys

bind= , XF86AudioMute,exec, $mute
bind= , XF86AudioNext, exec, $next
bind= , XF86AudioPrev, exec, $prev
bind= , XF86AudioPlay, exec, $playpause
binde= , XF86AudioRaiseVolume, exec,  $volumei
bindl= , XF86AudioLowerVolume, exec, $volumed
# bind= , xf86Rfkill, exec, $airplane
bind= , XF86MonBrightnessUp,exec, $backlighti
bind= , XF86MonBrightnessDown,exec,$backlightd
bind= , Print, exec, $screenshot

# Lid events
# When lid is down
# bind = ,switch:off:Lid Switch, exec, hyprctl dispatch dpms on eDP-1 
bind = ,switch:off:Lid Switch, exec, hyprlock
# When lid is up
# bind = ,switch:on:Lid Switch, exec, hyprlock
# bind = ,switch:on:Lid Switch, exec, hyprctl dispatch dpms off eDP-1 && swaylock -F


# Resize
binde = $mainMod SHIFT, J, resizeactive,-50 0
binde = $mainMod SHIFT, K, resizeactive,50 0

# Move focus
bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d
bind = ALT, tab, movefocus, l

# Move Window
bind = SUPER SHIFT, left, movewindow, l
bind = SUPER SHIFT, right, movewindow, r
bind = SUPER SHIFT, up, movewindow, u
bind = SUPER SHIFT, down, movewindow, d

# Switch workspaces
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 10
bind = CTRL ALT, right, workspace, e+1 
bind = CTRL ALT, left, workspace, e-1 
# bind = SUPER, right, workspace, e+1 
# bind = SUPER, left, workspace, e-1 

# Move active window to a workspace
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
bind = SUPER SHIFT, 0, movetoworkspace, 10

# Scroll through existing workspaces
bind = SUPER, mouse_down, workspace, e+1
bind = SUPER, mouse_up, workspace, e-1

# Move/resize windows
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow
