$airplane = ~/.config/hypr/scripts/airplane-mode.sh
$bar = pkill waybar || waybar
$backlightd = brightnessctl set 75- && exec sh ~/.config/hypr/scripts/brightness_notify
$backlighti = brightnessctl set 75+ && exec sh ~/.config/hypr/scripts/brightness_notify
$browser = firefox
$capture_notify = exec sh ~/.config/hypr/scripts/screenshot_notify
$connections = nm-connection-editor
$eww = eww kill
$files = nautilus
$ide = code
$incognito = $browser -private-window
# $incognito = $browser --incognito
$jupyter = jupyter notebook
$lock = hyprlock
$mainMod = SUPER
$music = lollypop
$mute = pamixer -t
$next = playerctl next
$prev = playerctl previous
$playpause = playerctl play-pause
$kill = pkill python3
$notify = dunst
$powerMenu = pkill wlogout || wlogout
# $rofi = pkill rofi || ~/.config/rofi/bin/launcher
$rofi = pkill rofi || rofi -show drun
$screenshot = grim -g "$(slurp)" ~/Pictures/Screenshots/$(date +"Screenshot_%Y-%m-%d_%H-%M-%S.png") && $capture_notify
$taskmgr = pkill btop || kitty btop
$term = kitty
$text = gnome-text-editor
$togglebar = pkill -SIGUSR1 '^waybar$'
$volumed = pamixer -d 5 && exec sh ~/.config/hypr/scripts/volume_notify
$volumei = pamixer -i 5 && exec sh ~/.config/hypr/scripts/volume_notify

